// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rdsfutjzzrhzjowppvgv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkc2Z1dGp6enJoempvd3Bwdmd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyOTU5MDcsImV4cCI6MjA1Njg3MTkwN30.K1EyVJELe5WT1tCsh-MiFvhKOeLY5iWy8tdEQsUNi8I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);